# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20150815_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championstat',
            old_name='armorperlevel',
            new_name='armor_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='attackdamage',
            new_name='attack_damage',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='attackdamageperlevel',
            new_name='attack_damage_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='attackrange',
            new_name='attack_range',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='attackspeedoffset',
            new_name='attack_speed_offset',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='attackspeedperlevel',
            new_name='attack_speed_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='critperlevel',
            new_name='crit_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='hpperlevel',
            new_name='hp_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='hpregen',
            new_name='hp_regen',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='hpregenperlevel',
            new_name='hp_regen_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='movespeed',
            new_name='move_speed',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='mpperlevel',
            new_name='mp_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='mpregen',
            new_name='mp_regen',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='mpregenperlevel',
            new_name='mp_regen_per_level',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='spellblock',
            new_name='spell_block',
        ),
        migrations.RenameField(
            model_name='championstat',
            old_name='spellblockperlevel',
            new_name='spell_block_per_level',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatArmorMod',
            new_name='flat_armor_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatAttackSpeedMod',
            new_name='flat_attack_speed_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatBlockMod',
            new_name='flat_block_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatCritChanceMod',
            new_name='flat_crit_chance_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatCritDamageMod',
            new_name='flat_crit_damage_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatEXPBonus',
            new_name='flat_energy_pool_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatEnergyPoolMod',
            new_name='flat_energy_regen_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatEnergyRegenMod',
            new_name='flat_exp_bonus',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatHPPoolMod',
            new_name='flat_hp_pool_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatHPRegenMod',
            new_name='flat_hp_regen_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatMPPoolMod',
            new_name='flat_magic_damage_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatMPRegenMod',
            new_name='flat_movement_speed_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatMagicDamageMod',
            new_name='flat_mp_pool_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatMovementSpeedMod',
            new_name='flat_mp_regen_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatPhysicalDamageMod',
            new_name='flat_physical_damage_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='FlatSpellBlockMod',
            new_name='flat_spell_block_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentArmorMod',
            new_name='percent_armor_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentAttackSpeedMod',
            new_name='percent_attack_speed_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentBlockMod',
            new_name='percent_block_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentCritChanceMod',
            new_name='percent_crit_chance_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentCritDamageMod',
            new_name='percent_crit_damage_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentDodgeMod',
            new_name='percent_dodge_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentEXPBonus',
            new_name='percent_exp_bonus',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentHPPoolMod',
            new_name='percent_hp_pool_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentHPRegenMod',
            new_name='percent_hp_regen_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentLifeStealMod',
            new_name='percent_life_steal_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentMPPoolMod',
            new_name='percent_magic_damage_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentMPRegenMod',
            new_name='percent_movement_speed_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentMagicDamageMod',
            new_name='percent_mp_pool_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentMovementSpeedMod',
            new_name='percent_mp_regen_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentPhysicalDamageMod',
            new_name='percent_physical_damage_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentSpellBlockMod',
            new_name='percent_spell_block_mod',
        ),
        migrations.RenameField(
            model_name='itemstat',
            old_name='PercentSpellVampMod',
            new_name='percent_spell_vamp_mod',
        ),
    ]
